### ISSUE TITLE
Javascripts in PDF aren't recognized

### ISSUE THREAD

**Issue by Lachrimae93** [farling42/fvtt-pdf-pager#116]
I've made a pdf character sheet for a system and tried to use this for it but there were some issues off the bat.

The sheet involves having checkboxes for stats (one stat has a check box that progresses from 1 to 9 so there can be a max of 9 boxes checked). To save the hassle of having to click all nine boxes to uncheck later on, I made a javascript button that deselects those checkboxes immediately when pressed.

The problem is, PDF Pager does not read this script. It shows the button as an error. I found that if I ticked the read only option in the settings then the button and every other script I put in the PDF works fine BUT the issue then is that I can't edit anything on the text fields and any changes made (check boxes ticked) aren't saved and the PDF goes back to 0 when it's closed and opened.

@farling42  I saw you had an issue open that was regarding java scripts but no updates on it. Is there any chance this can be fixed?

**Comment by farling42** [comment]
Is the javascript button coded directly inside the PDF?

The other issue about javascript was referring to triggering some javascript that was supplied from the Foundry side, rather than being internal to the PDF.

**Comment by farling42** [comment]
Could you provide me with a copy of the PDF, and explain which fields within the PDF you are trying to get working?

**Comment by Lachrimae93** [comment]
> Is the javascript button coded directly inside the PDF?
> 
> The other issue about javascript was referring to triggering some javascript that was supplied from the Foundry side, rather than being internal to the PDF.

Yup the java script is in the PDF file itself. I'm attaching a copy here
[Girl By Moonlight - Playbook - Enigma.pdf](https://github.com/user-attachments/files/17326554/Girl.By.Moonlight.-.Playbook.-.Enigma.pdf)
So if you see the dots on the stress row for example (there's 9 of them) there is a script that makes it so that if I press a dot, it also triggers all the other dots before it (if you click on the 5th one, dots 1 through 4 trigger) and then I made a button that is placed directly on top of the word "Stress" that, when pressed, clears all the dots.


These functions only work when I tick the setting that basically makes the PDF read only and the text fields cannot be edited and any changes to the sheet will not be saved when it's closed.

**Comment by farling42** [comment]
This should be fixed in 1.5.3

**Comment by Lachrimae93** [comment]
> This should be fixed in 1.5.3

Just saw that the scripts work but the buttons with scripts still don't work. Is that something that can't be fixed?
![image](https://github.com/user-attachments/assets/b83fae31-c8f5-4c44-956d-dceb76790a45)

**Comment by Lachrimae93** [comment]
I just did some checks and apparently the module does not allow for the "Reset Form" function in a PDF. 
[Playbook - Enigma.pdf](https://github.com/user-attachments/files/17339044/Playbook.-.Enigma.pdf)
So in the stress dots of this PDF, i set the first dot to reset all the other dots (meaning if I click the first dot after the succeeding dots are filled, it will reset the whole tracker). This function is not recognized in PDF pager.

@farling42 just checking if this is something that can't be fixed.

**Comment by farling42** [comment]
> I just did some checks and apparently the module does not allow for the "Reset Form" function in a PDF. [Playbook - Enigma.pdf](https://github.com/user-attachments/files/17339044/Playbook.-.Enigma.pdf) So in the stress dots of this PDF, i set the first dot to reset all the other dots (meaning if I click the first dot after the succeeding dots are filled, it will reset the whole tracker). This function is not recognized in PDF pager.
> 
> @farling42 just checking if this is something that can't be fixed.

It looks like this particular function does not work with the pdf.js library that Foundry uses. The simplest test is to disable the PDF Pager module and view the PDF in a journal page, to test if certain JS functions inside the PDF work.

**Comment by farling42** [comment]
> > This should be fixed in 1.5.3
> 
> Just saw that the scripts work but the buttons with scripts still don't work. Is that something that can't be fixed? ![image](https://private-user-images.githubusercontent.com/74852834/375582851-b83fae31-c8f5-4c44-956d-dceb76790a45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MzgyODIsIm5iZiI6MTcyODYzNzk4MiwicGF0aCI6Ii83NDg1MjgzNC8zNzU1ODI4NTEtYjgzZmFlMzEtYzhmNS00YzQ0LTk1NmQtZGNlYjc2NzkwYTQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDA5MTMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1NmE5NzQxOGYwOGYyY2FlYzdhZDI1NGZkMzc4YzdmZGY5Zjg4YWIyYWYyNjIzZGY2ZGEzOThhN2UzZTdmYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.d-60bbQ956rwC7AX6Dm0Mj-6sx5EDpHsRkE7e4exyC8)

Which parts of the PDF are the buttons that don't work?

**Comment by Lachrimae93** [comment]
> > > This should be fixed in 1.5.3
> > 
> > 
> > Just saw that the scripts work but the buttons with scripts still don't work. Is that something that can't be fixed? ![image]
> 
> Which parts of the PDF are the buttons that don't work?

It's the part where if you fill up the dots on the right of "Stress" then click the very first stress dot in the sequence, they should all clear out. I did away with the buttons but this function doesn't work. it's a "Reset Form" function in PDF

**Comment by farling42** [comment]
> > > > This should be fixed in 1.5.3
> > > 
> > > 
> > > Just saw that the scripts work but the buttons with scripts still don't work. Is that something that can't be fixed? ![image]
> > 
> > 
> > Which parts of the PDF are the buttons that don't work?
> 
> It's the part where if you fill up the dots on the right of "Stress" then click the very first stress dot in the sequence, they should all clear out. I did away with the buttons but this function doesn't work. it's a "Reset Form" function in PDF

Ah OK. It seems that it doesn't work with the pdf.js library that Foundry uses.

**Comment by Lachrimae93** [comment]
> > > > > This should be fixed in 1.5.3
> > > > 
> > > > 
> > > > Just saw that the scripts work but the buttons with scripts still don't work. Is that something that can't be fixed? ![image]
> > > 
> > > 
> > > Which parts of the PDF are the buttons that don't work?
> > 
> > 
> > It's the part where if you fill up the dots on the right of "Stress" then click the very first stress dot in the sequence, they should all clear out. I did away with the buttons but this function doesn't work. it's a "Reset Form" function in PDF
> 
> Ah OK. It seems that it doesn't work with the pdf.js library that Foundry uses.

So that's not something that can be fixed? No  worries if not. Do you know a possible workaround?

**Comment by farling42** [comment]
Your previous solution of simply ticking all boxes to left still works, maybe just add to untick all boxes to the right. I've never looked at how JS works inside PDFs though.

**Comment by Lachrimae93** [comment]
> Your previous solution of simply ticking all boxes to left still works, maybe just add to untick all boxes to the right. I've never looked at how JS works inside PDFs though.

Well what I did was have a button that does the same thing (clear the form) but those buttons don't work. It's okay if it doesn't work I appreciate all the help anyway!

**Comment by Lachrimae93** [comment]
> If you only want it to work with Foundry, then you could use a mapping object to handle store a single value. For each button, set a getValue which returns true if the value >= the button's value, and a setValue function which sets the variable to the value on the button.

That's unfortunately beyond my skill level but yeah I did just want it for foundry. Anyway, if there's no other fix for this that can be done from the module's end happy to have this closed.
